name: FalconStack CI


on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Verify Dockerfile exists
        run: test -f Dockerfile


      - name: Build Docker Image
        run: |
          docker build -t falconstack-ci .


      - name: Show Built Images
        run: |
          docker images


      - name: Success
        run: echo "Docker build successful"
